Fixes: after project close, open or create project fails
See issue #96.

This change creates a new class disconnectAll() to ensure that all
connections are disconnected for a specific signal and slot.  Now when
a project is closed, the UI signals are disconnected.  As before,
these signals and slots are connected when a project is opened.

Because Manuskript permits working on only one project at a time, the
menu items for File Open and Recents are disabled after a project is
loaded.  These menu items are enabled when a project is closed.

Prior to this commit, subsequent open project selections would
complain with the following message:

  TypeError: connection is not unique