Fix Travix CI build error on OSX installing python3
The Travis CI builds have been failing with the following message:

    The command "if [ "$TRAVIS_OS_NAME" = "osx" ]; then \
                 bash package/prepare_osx.sh; fi"       \
     failed and exited with 1 during .

This above line of code is from .travis.yml.  Further examination of
the log from executing package/prepare_osx.sh shows the following
message:

    <snip>
    brew install python3 enchant
    Error: python 2.7.12_1 is already installed
    To upgrade to 3.6.5, run `brew upgrade python`
    <snip>

Based on this message it appears that the method to install python3
has changed.  Hence change command to upgrade python 2.x to 3.x.